package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActividadAgregada generated by hbm2java
 */
@Entity
@Table(name="actividad_agregada")
public class ActividadAgregada  implements java.io.Serializable {


     private long codigo;
     private ActividadGenerica actividadGenerica;
     private long CClaseAgregada;
     private String descripcion;

    public ActividadAgregada() {
    }

	
    public ActividadAgregada(long codigo, ActividadGenerica actividadGenerica, long CClaseAgregada) {
        this.codigo = codigo;
        this.actividadGenerica = actividadGenerica;
        this.CClaseAgregada = CClaseAgregada;
    }
    public ActividadAgregada(long codigo, ActividadGenerica actividadGenerica, long CClaseAgregada, String descripcion) {
       this.codigo = codigo;
       this.actividadGenerica = actividadGenerica;
       this.CClaseAgregada = CClaseAgregada;
       this.descripcion = descripcion;
    }
   
     @Id 
    
    @Column(name="codigo", unique=true, nullable=false)
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_actividad", nullable=false)
    public ActividadGenerica getActividadGenerica() {
        return this.actividadGenerica;
    }
    
    public void setActividadGenerica(ActividadGenerica actividadGenerica) {
        this.actividadGenerica = actividadGenerica;
    }
    
    @Column(name="c_clase_agregada", nullable=false)
    public long getCClaseAgregada() {
        return this.CClaseAgregada;
    }
    
    public void setCClaseAgregada(long CClaseAgregada) {
        this.CClaseAgregada = CClaseAgregada;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


