package co.org.conte.sgm.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asociacion generated by hbm2java
 */
@Entity
@Table(name="asociacion")
public class Asociacion extends BaseEntity{
    
    @Id     
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="codigo", unique=true, nullable=false)
    private int codigo;
    
    @Column(name="sigla", length=45)
    private String sigla;
    
    @Column(name="nombre", length=45)
    private String nombre;
    
    @Column(name="direccion", length=45)
    private String direccion;
    
    @Column(name="telefono")
    private String telefono;
        
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="c_ciudad")
    private Ciudad ciudad;
    
    @Column(name="email")
    private String email;
    
    @Column(name="email_alterno")
    private String emailAlterno;
    
    @Column(name="presidente")
    private String presidente;
    
    @Column(name="celular_presidente")
    private String celularPresidente;
    
    @Column(name="nit")
    private String nit;
    
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_convenio", length=10)
    private Date fechaConvenio;
    
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_vigencia", length=10)
    private Date fechaVigencia;
    
    @Column(name="firmante_convenio")
    private String firmanteConvenio;
    
    @Column(name="cargo_firmante")
    private String cargoFirmante;
    
    @Column(name="celular")
    private String celular;
    
    @Column(name="estado")
    private Boolean estado;
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="asociacion")
    private Set<Solicitud> solicituds = new HashSet(0);
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="asociacion")
    private Set<Inspector> inspectors = new HashSet(0);
    
    public Asociacion() {
    }
    
    public Asociacion(int codigo) {
        this.codigo = codigo;
    }
    public Asociacion(int codigo, String nombre, Ciudad ciudad, String direccion, String telefono, String celular, String email, Set<Solicitud> solicitudes, Set<Inspector> inspectores) {
        
        this.codigo = codigo;
        this.nombre = nombre;
        this.ciudad = ciudad;
        this.direccion = direccion;
        this.telefono = telefono;
        this.celular = celular;
        this.email = email;
        this.solicituds = solicitudes;
        this.inspectors = inspectores;
    }

    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getSigla() {
        return sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public Ciudad getCiudad() {
        return ciudad;
    }

    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmailAlterno() {
        return emailAlterno;
    }

    public void setEmailAlterno(String emailAlterno) {
        this.emailAlterno = emailAlterno;
    }

    public String getPresidente() {
        return presidente;
    }

    public void setPresidente(String presidente) {
        this.presidente = presidente;
    }

    public String getCelularPresidente() {
        return celularPresidente;
    }

    public void setCelularPresidente(String celularPresidente) {
        this.celularPresidente = celularPresidente;
    }

    public String getNit() {
        return nit;
    }

    public void setNit(String nit) {
        this.nit = nit;
    }

    public Date getFechaConvenio() {
        return fechaConvenio;
    }

    public void setFechaConvenio(Date fechaConvenio) {
        this.fechaConvenio = fechaConvenio;
    }

    public Date getFechaVigencia() {
        return fechaVigencia;
    }

    public void setFechaVigencia(Date fechaVigencia) {
        this.fechaVigencia = fechaVigencia;
    }

    public String getFirmanteConvenio() {
        return firmanteConvenio;
    }

    public void setFirmanteConvenio(String firmanteConvenio) {
        this.firmanteConvenio = firmanteConvenio;
    }

    public String getCargoFirmante() {
        return cargoFirmante;
    }

    public void setCargoFirmante(String cargoFirmante) {
        this.cargoFirmante = cargoFirmante;
    }

    public String getCelular() {
        return celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Set<Solicitud> getSolicituds() {
        return solicituds;
    }

    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }

    public Set<Inspector> getInspectors() {
        return inspectors;
    }

    public void setInspectors(Set<Inspector> inspectors) {
        this.inspectors = inspectors;
    }
}