package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CausalInadmision generated by hbm2java
 */
@Entity
@Table(name="causal_inadmision")
public class CausalInadmision  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String descripcion;
     private Set<Inadmision> inadmisiones = new HashSet(0);

    public CausalInadmision() {
    }

	
    public CausalInadmision(int codigo) {
        this.codigo = codigo;
    }
    public CausalInadmision(int codigo, String nombre, String descripcion, Set<Inadmision> inadmisiones) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.inadmisiones = inadmisiones;
    }
   
     @Id 
    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="causalInadmision")
    public Set<Inadmision> getInadmisions() {
        return this.inadmisiones;
    }
    
    public void setInadmisions(Set<Inadmision> inadmisiones) {
        this.inadmisiones = inadmisiones;
    }




}


