package co.org.conte.sgm.entity;
// Generated 25/02/2013 04:11:50 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClaseGenerica generated by hbm2java
 */
@Entity
@Table(name="clase_generica"
    ,catalog="sgm_conte_dev"
)
public class ClaseGenerica_1  implements java.io.Serializable {


     private Integer codigo;
     private String nombre;
     private Boolean estado;

    public ClaseGenerica_1() {
    }

    public ClaseGenerica_1(String nombre, Boolean estado) {
       this.nombre = nombre;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="codigo", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="nombre", length=60)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


