package co.org.conte.sgm.entity;
// Generated 30/10/2012 11:23:25 AM by Hibernate Tools 3.2.
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClaseGenerica generated by hbm2java
 */
@Entity
@Table(name="clase_generica")
public class ClaseGenerica extends BaseEntity{

    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="codigo", unique=true, nullable=false)    
    private Integer codigo;
    
    @Column(name="nombre", length=45)
    private String nombre;
    
    @Column(name="estado", length=1)
    private boolean estado;
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="claseGenerica")
    private Set<ActividadGenerica> actividadGenericas = new HashSet(0);

    public ClaseGenerica() {
    }

	
    public ClaseGenerica(int codigo) {
        this.codigo = codigo;
    }
    public ClaseGenerica(int codigo, String nombre, Set actividadGenericas) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.actividadGenericas = actividadGenericas;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public boolean getEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
    public Set<ActividadGenerica> getActividadGenericas() {
        return this.actividadGenericas;
    }
    
    public void setActividadGenericas(Set actividadGenericas) {
        this.actividadGenericas = actividadGenericas;
    }

    @Override
    public String toString() {
        return this.getNombre();
    }
}