package co.org.conte.sgm.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento")
public class Departamento  extends BaseEntity{

    @Id     
    @GeneratedValue(strategy= GenerationType.AUTO)
    @Column(name="codigo", unique=true, nullable=false)
    private int codigo;
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_pais", nullable=false)
    private Pais pais;
    
    @Column(name="nombre", length=60)
    private String nombre;
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="departamento")
    private Set<Ciudad> ciudads = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int codigo, Pais pais) {
        this.codigo = codigo;
        this.pais = pais;
    }
    public Departamento(int codigo, Pais pais, String nombre, Set ciudads) {
       this.codigo = codigo;
       this.pais = pais;
       this.nombre = nombre;
       this.ciudads = ciudads;
    }
       
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
        
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set<Ciudad> getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 23 * hash + this.codigo;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Departamento other = (Departamento) obj;
        if (this.codigo != other.codigo) {
            return false;
        }
        return true;
    }
    
    
}