package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="estado")
public class Estado  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String descripcion;
     private Character activo;
     private Set<Inadmision> inadmisions = new HashSet(0);
     private Set solicituds = new HashSet(0);
     private Set logSolicituds = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int codigo) {
        this.codigo = codigo;
    }
    public Estado(int codigo, String nombre, String descripcion, Character activo, Set<Inadmision> inadmisiones, Set solicituds, Set logSolicituds) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.activo = activo;
       this.inadmisions = inadmisiones;
       this.solicituds = solicituds;
       this.logSolicituds = logSolicituds;
    }
   
     @Id 
    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="activo", length=1)
    public Character getActivo() {
        return this.activo;
    }
    
    public void setActivo(Character activo) {
        this.activo = activo;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set<Inadmision> getInadmisions() {
        return this.inadmisions;
    }
    
    public void setInadmisions(Set<Inadmision> inadmisions) {
        this.inadmisions = inadmisions;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set<Solicitud> getLogSolicituds() {
        return this.logSolicituds;
    }
    
    public void setLogSolicituds(Set logSolicituds) {
        this.logSolicituds = logSolicituds;
    }




}


