package co.org.conte.sgm.entity;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evaluacion generated by hbm2java
 */
@Entity
@Table(name="evaluacion")
public class Evaluacion  implements java.io.Serializable {

    private EvaluacionId id;
    private ActividadGenerica activity;
    private Item item;
    private Solicitud solicitud;
    private String documento;
    private Date fecha;
     

    public Evaluacion() {
    }

    public Evaluacion(EvaluacionId id, Solicitud solicitud, Item item) {
       this.id = id;
       this.solicitud = solicitud;
       this.item = item;
    }
    
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="solicitudId", column=@Column(name="solicitud_id", nullable=false) ), 
        @AttributeOverride(name="activityId", column=@Column(name="activity_id", nullable=false) ), 
        @AttributeOverride(name="itemId", column=@Column(name="item_id", nullable=false) ) } )
    public EvaluacionId getId() {
        return this.id;
    }
    
    public void setId(EvaluacionId id) {
        this.id = id;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="item_id", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="solicitud_id", nullable=false, insertable=false, updatable=false)
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="activity_id", nullable=false, insertable=false, updatable=false)
    public ActividadGenerica getActivity() {
        return this.activity;
    }
    
    public void setActivity(ActividadGenerica activity) {
        this.activity = activity;
    }

    @Column(name="documento", length=20)
    public String getDocumento() {
        return documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    
}