package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FormatoClaseId generated by hbm2java
 */
@Embeddable
public class FormatoActividadId  implements java.io.Serializable {

    private int activityId;
    private int formatId;
    private int itemId;

    public FormatoActividadId() {
    }

    public FormatoActividadId(int formatId, int activityId) {
       this.formatId = formatId;
       this.activityId = activityId;
    }
   
    @Column(name="c_actividad", nullable=false)
    public int getActivityId() {
        return activityId;
    }

    public void setActivityId(int activityId) {
        this.activityId = activityId;
    }

    @Column(name="c_formato", nullable=false)
    public int getFormatId() {
        return formatId;
    }

    public void setFormatId(int formatId) {
        this.formatId = formatId;
    }

    @Column(name="item_id", nullable=false)
    public int getItemId() {
        return itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    

    @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FormatoActividadId) ) return false;
		 FormatoActividadId castOther = ( FormatoActividadId ) other; 
         
		 return (
                         this.getFormatId()==castOther.getFormatId())
                         && (this.getActivityId()==castOther.getActivityId());
   }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + this.activityId;
        hash = 79 * hash + this.formatId;
        hash = 79 * hash + this.itemId;
        return hash;
    }
   



}


