package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * FormatoEstudio generated by hbm2java
 */
@Entity
@Table(name="formato_estudio")
public class FormatoEstudio extends BaseEntity{


     private Integer codigo;
//     private String nombre;
     private boolean estado;
     private TituloAcademico tituloAcademico;
     private Set<SolicitudFormato> solicitudFormatos = new HashSet(0);
     private Set<FormatoActividad> formatoActividades = new HashSet(0);

    public FormatoEstudio() {
    }

	
    public FormatoEstudio(int codigo) {
        this.codigo = codigo;
    }
    public FormatoEstudio(int codigo, Boolean estado, Set solicitudFormatos, Set formatoActividades) {
       this.codigo = codigo;
//       this.nombre = nombre;
       this.estado = estado;
       this.solicitudFormatos = solicitudFormatos;
       this.formatoActividades = formatoActividades;
    }
   
    @Id     
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="codigo", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    
//    @Column(name="nombre", length=45)
//    public String getNombre() {
//        return this.nombre;
//    }
    
//    public void setNombre(String nombre) {
//        this.nombre = nombre;
//    }

    @OneToOne()  
    @JoinColumn(name = "c_titulo", nullable = false)    
    public TituloAcademico getTituloAcademico() {
        return tituloAcademico;
    }

    public void setTituloAcademico(TituloAcademico tituloAcademico) {
        this.tituloAcademico = tituloAcademico;
    }
    
    @Column(name="estado", length=45)
    public boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="formatoEstudio")
    public Set<SolicitudFormato> getSolicitudFormatos() {
        return this.solicitudFormatos;
    }
    
    public void setSolicitudFormatos(Set<SolicitudFormato> solicitudFormatos) {
        this.solicitudFormatos = solicitudFormatos;
    }
    
    @OneToMany(cascade = {CascadeType.MERGE}, fetch=FetchType.LAZY, mappedBy="formatoEstudio")
    public Set<FormatoActividad> getFormatoActividades() {
        return this.formatoActividades;
    }
    
    public void setFormatoActividades(Set<FormatoActividad> formatoActividad) {
        this.formatoActividades = formatoActividad;
    }
}