package co.org.conte.sgm.entity;
// Generated 30/10/2012 11:23:25 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FormatoClase generated by hbm2java
 */
@Entity
@Table(name="formato_actividad")
public class FormatoActividad extends BaseEntity{
    
     private FormatoActividadId id;
     private FormatoEstudio formatoEstudio;
     private ActividadGenerica actividadGenerica;
     private Item item;

    public FormatoActividad() {
    }

	
    public FormatoActividad(FormatoActividadId id, FormatoEstudio formatoEstudio, ActividadGenerica actividadGenerica) {
        this.id = id;
        this.formatoEstudio = formatoEstudio;
        this.actividadGenerica = actividadGenerica;
    }
    public FormatoActividad(FormatoActividadId id, FormatoEstudio formatoEstudio, ActividadGenerica actividadGenerica, Item item) {
       this.id = id;
       this.formatoEstudio = formatoEstudio;
       this.actividadGenerica = actividadGenerica;
       this.item = item;
    }
   
    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="formatId", column=@Column(name="c_formato", nullable=false) ), 
        @AttributeOverride(name="activityId", column=@Column(name="c_actividad", nullable=false) ) } )
    public FormatoActividadId getId() {
        return this.id;
    }
    
    public void setId(FormatoActividadId id) {
        this.id = id;
    }
    
    @ManyToOne(fetch= FetchType.LAZY)
    @JoinColumn(name="c_formato", nullable=false, insertable=false, updatable=false)
    public FormatoEstudio getFormatoEstudio() {
        return this.formatoEstudio;
    }
    
    public void setFormatoEstudio(FormatoEstudio formatoEstudio) {
        this.formatoEstudio = formatoEstudio;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="c_actividad", nullable=false, insertable=false, updatable=false)
    public ActividadGenerica getActividadGenerica() {
        return this.actividadGenerica;
    }
    
    public void setActividadGenerica(ActividadGenerica actividadGenerica) {
        this.actividadGenerica = actividadGenerica;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="item_id", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FormatoActividad other = (FormatoActividad) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }
}


