package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Inadmision generated by hbm2java
 */
@Entity
@Table(name="inadmision")
public class Inadmision  implements java.io.Serializable {


     private Integer codigo;
     private Estado estado;
     private CausalInadmision causalInadmision;
     private Solicitud solicitud;
     private String descripcion;

    public Inadmision() {
    }

	
    public Inadmision(Estado estado, CausalInadmision causalInadmision, Solicitud solicitud) {
        this.estado = estado;
        this.causalInadmision = causalInadmision;
        this.solicitud = solicitud;
    }
    public Inadmision(Estado estado, CausalInadmision causalInadmision, Solicitud solicitud, String descripcion) {
       this.estado = estado;
       this.causalInadmision = causalInadmision;
       this.solicitud = solicitud;
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="codigo", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_estado", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_causal", nullable=false)
    public CausalInadmision getCausalInadmision() {
        return this.causalInadmision;
    }
    
    public void setCausalInadmision(CausalInadmision causalInadmision) {
        this.causalInadmision = causalInadmision;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_solicitud", nullable=false)
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


