package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Inspector generated by hbm2java
 */
@Entity
@Table(name="inspector")
public class Inspector extends BaseEntity{


     private int codigo;
     private Asociacion asociacion;
     private Ciudad ciudad;
     private String documento;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String telefono;
     private String celular;
     private String email;
     private Set<Solicitud> solicituds = new HashSet(0);

    public Inspector() {
    }

	
    public Inspector(int codigo, Asociacion asociacion, Ciudad ciudad) {
        this.codigo = codigo;
        this.asociacion = asociacion;
        this.ciudad = ciudad;
    }
    public Inspector(int codigo, Asociacion asociacion, Ciudad ciudad, String documento, String nombres, String apellidos, String direccion, String telefono, String celular, String email, Set<Solicitud> solicitudes) {
       this.codigo = codigo;
       this.asociacion = asociacion;
       this.ciudad = ciudad;
       this.documento = documento;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.email = email;
       this.solicituds = solicitudes;
    }
   
     @Id 
    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_asociacion", nullable=false)
    public Asociacion getAsociacion() {
        return this.asociacion;
    }
    
    public void setAsociacion(Asociacion asociacion) {
        this.asociacion = asociacion;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="c_ciudad", nullable=false)
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    
    @Column(name="documento", length=20)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    
    @Column(name="nombres", length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="apellidos", length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="celular", length=20)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="inspector")
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


