package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InstitucionEducativa generated by hbm2java
 */
@Entity
@Table(name="institucion_educativa")
public class InstitucionEducativa  extends BaseEntity{


     private Integer codigo;
     private String sigla;
     private String nombre;
     private String registroMen;
     private Boolean estado;
     private Set tituloAcademicos = new HashSet(0);

    public InstitucionEducativa() {
    }

	
    public InstitucionEducativa(int codigo) {
        this.codigo = codigo;
    }
    public InstitucionEducativa(int codigo, String nombre, String registroMen, Set tituloAcademicos) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.registroMen = registroMen;
       this.tituloAcademicos = tituloAcademicos;
    }
   
    @Id     
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="codigo", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    @Column(name="sigla", length=45)
    public String getSigla() {
        return sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="registro_men", length=45)
    public String getRegistroMen() {
        return this.registroMen;
    }
    
    public void setRegistroMen(String registroMen) {
        this.registroMen = registroMen;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="institucionEducativa")
    public Set<TituloAcademico> getTituloAcademicos() {
        return this.tituloAcademicos;
    }
    
    public void setTituloAcademicos(Set tituloAcademicos) {
        this.tituloAcademicos = tituloAcademicos;
    }

    @Column(name="estado", length=1)
    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    
    @Override
    public Serializable findId(){
        return getCodigo();
        
    }

    @Override
    public String toString() {
        return this.getNombre();
    }
    
    




}


