package co.org.conte.sgm.entity;
// Generated 25/02/2013 04:11:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item")
public class Item  extends BaseEntity{

     private int id;
     private String name;
     private Set actividadGenericas = new HashSet(0);
     private Set<Evaluacion> evaluaciones = new HashSet<Evaluacion>(0);

    public Item() {
    }

	
    public Item(int id) {
        this.id = id;
    }
    public Item(int id, String name, Set actividadGenericas) {
       this.id = id;
       this.name = name;
       this.actividadGenericas = actividadGenericas;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="activity_item", joinColumns = { 
        @JoinColumn(name="item_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="activity_id", nullable=false, updatable=false) })
    public Set<ActividadGenerica> getActividadGenericas() {
        return this.actividadGenericas;
    }
    
    public void setActividadGenericas(Set actividadGenericas) {
        this.actividadGenericas = actividadGenericas;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="item")
    public Set<Evaluacion> getEvaluacions() {
        return this.evaluaciones;
    }
    
    public void setEvaluacions(Set evaluaciones) {
        this.evaluaciones = evaluaciones;
    }

    @Override
    public String toString() {
        return getName();
    }
    
    @Override
    public boolean equals(Object other) {
         if ( (this == other ) ) {
             return true;
         }
         if ( (other == null ) ) {
             return false;
         }
         if ( !(other instanceof ActividadGenerica) ) {
             return false;
         } else {
             Item castOther = ( Item ) other;
             return (this.getId() == castOther.getId()) ? true : false;
         } 
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 29 * hash + this.id;
        return hash;
    }
    
    
}


