package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LogPqrs generated by hbm2java
 */
@Entity
@Table(name="log_pqrs")
public class LogPqrs  implements java.io.Serializable {


     private Long codigo;
     private Pqrs pqrs;
     private String descripcion;
     private String accion;

    public LogPqrs() {
    }

	
    public LogPqrs(Pqrs pqrs) {
        this.pqrs = pqrs;
    }
    public LogPqrs(Pqrs pqrs, String descripcion, String accion) {
       this.pqrs = pqrs;
       this.descripcion = descripcion;
       this.accion = accion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="codigo", unique=true, nullable=false)
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_pqrs", nullable=false)
    public Pqrs getPqrs() {
        return this.pqrs;
    }
    
    public void setPqrs(Pqrs pqrs) {
        this.pqrs = pqrs;
    }
    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="accion", length=10)
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }




}


