package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LogTecnico generated by hbm2java
 */
@Entity
@Table(name="log_tecnico")
public class LogTecnico  implements java.io.Serializable {


     private Long codigo;
     private Tecnico tecnico;
     private String descripcion;
     private String accion;

    public LogTecnico() {
    }

	
    public LogTecnico(Tecnico tecnico) {
        this.tecnico = tecnico;
    }
    public LogTecnico(Tecnico tecnico, String descripcion, String accion) {
       this.tecnico = tecnico;
       this.descripcion = descripcion;
       this.accion = accion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="codigo", unique=true, nullable=false)
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_tecnico", nullable=false)
    public Tecnico getTecnico() {
        return this.tecnico;
    }
    
    public void setTecnico(Tecnico tecnico) {
        this.tecnico = tecnico;
    }
    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="accion", length=10)
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }




}


