package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogUsuario generated by hbm2java
 */
@Entity
@Table(name="log_usuario")
public class LogUsuario  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy=IDENTITY)    
    @Column(name="codigo", unique=true, nullable=false)
    private Long codigo;
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_usuario", nullable=false)
    private Usuario usuario;
    
    @Column(name="usuario_modificado")
    private String usuarioModificado;
    
    @Column(name="descripcion", length=100)
    private String descripcion;
    
    @Column(name="accion", length=100)
    private String accion;
    
    @Column(name="c_usuario_modificado")
    private int codUsuarioModificador;
    
    @Column(name="usuario")
    private String usuarioModificador;
    
    @Column(name="direccion_ip")
    private String ip;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    private Date fecha;
    
    public LogUsuario() {
    }

    public Long getCodigo() {
        return codigo;
    }

    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getUsuarioModificado() {
        return usuarioModificado;
    }

    public void setUsuarioModificado(String usuarioModificado) {
        this.usuarioModificado = usuarioModificado;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getAccion() {
        return accion;
    }

    public void setAccion(String accion) {
        this.accion = accion;
    }

    public int getCodUsuarioModificador() {
        return codUsuarioModificador;
    }

    public void setCodUsuarioModificador(int codUsuarioModificador) {
        this.codUsuarioModificador = codUsuarioModificador;
    }

    public String getUsuarioModificador() {
        return usuarioModificador;
    }

    public void setUsuarioModificador(String usuarioModificador) {
        this.usuarioModificador = usuarioModificador;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
}