package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Observacion generated by hbm2java
 */
@Entity
@Table(name="observacion")
public class Observacion  implements java.io.Serializable {


     private int codigo;
     private Solicitud solicitud;
     private Integer CEstado;
     private String descripcion;

    public Observacion() {
    }

	
    public Observacion(int codigo, Solicitud solicitud) {
        this.codigo = codigo;
        this.solicitud = solicitud;
    }
    public Observacion(int codigo, Solicitud solicitud, Integer CEstado, String descripcion) {
       this.codigo = codigo;
       this.solicitud = solicitud;
       this.CEstado = CEstado;
       this.descripcion = descripcion;
    }
   
     @Id 
    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_solicitud", nullable=false)
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    
    @Column(name="c_estado")
    public Integer getCEstado() {
        return this.CEstado;
    }
    
    public void setCEstado(Integer CEstado) {
        this.CEstado = CEstado;
    }
    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


