package co.org.conte.sgm.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pagina generated by hbm2java
 */
@Entity
@Table(name="pagina")
public class Pagina  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String enlace;
     private Character activo;
     private String observaciones;
     private Set rolPaginas = new HashSet(0);

    public Pagina() {
    }

	
    public Pagina(int codigo) {
        this.codigo = codigo;
    }
    public Pagina(int codigo, String nombre, String enlace, Character activo, String observaciones, Set rolPaginas) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.enlace = enlace;
       this.activo = activo;
       this.observaciones = observaciones;
       this.rolPaginas = rolPaginas;
    }
   
     @Id 
    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="nombre", length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="enlace", length=45)
    public String getEnlace() {
        return this.enlace;
    }
    
    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }
    
    @Column(name="activo", length=1)
    public Character getActivo() {
        return this.activo;
    }
    
    public void setActivo(Character activo) {
        this.activo = activo;
    }
    
    @Column(name="observaciones", length=45)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pagina")
    public Set<RolPagina> getRolPaginas() {
        return this.rolPaginas;
    }
    
    public void setRolPaginas(Set rolPaginas) {
        this.rolPaginas = rolPaginas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 61 * hash + this.codigo;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Pagina other = (Pagina) obj;
        if (this.codigo != other.codigo) {
            return false;
        }
        return true;
    }
    
    

  
}


