package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name="perfil")
public class Perfil  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private Character activo;
     private String descripcion;
     private Set<PerfilRol> perfilRols = new HashSet(0);
     private Set<Usuario> usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(int codigo) {
        this.codigo = codigo;
    }
    public Perfil(int codigo, String nombre, Character activo, String descripcion, Set perfilRols, Set usuarios) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.activo = activo;
       this.descripcion = descripcion;
       this.perfilRols = perfilRols;
       this.usuarios = usuarios;
    }
   
     @Id 
    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="activo", length=1)
    public Character getActivo() {
        return this.activo;
    }
    
    public void setActivo(Character activo) {
        this.activo = activo;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="perfil")
    public Set<PerfilRol> getPerfilRols() {
        return this.perfilRols;
    }
    
    public void setPerfilRols(Set perfilRols) {
        this.perfilRols = perfilRols;
    }
    
    //@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="perfil")
    @OneToMany(fetch=FetchType.LAZY, mappedBy="perfil")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public String toString() {
        return getNombre();
    }

    



}


