package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilRolId generated by hbm2java
 */
@Embeddable
public class PerfilRolId  implements java.io.Serializable {


     private Integer CPerfil;
     private Integer CRol;

    public PerfilRolId() {
    }

    public PerfilRolId(int CPerfil, int CRol) {
       this.CPerfil = CPerfil;
       this.CRol = CRol;
    }
   

    @Column(name="c_perfil", nullable=false)
    public Integer getCPerfil() {
        return this.CPerfil;
    }
    
    public void setCPerfil(Integer CPerfil) {
        this.CPerfil = CPerfil;
    }

    @Column(name="c_rol", nullable=false)
    public Integer getCRol() {
        return this.CRol;
    }
    
    public void setCRol(Integer CRol) {
        this.CRol = CRol;
    }


    @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerfilRolId) ) return false;
		 PerfilRolId castOther = ( PerfilRolId ) other; 
         
		 return (this.getCPerfil()==castOther.getCPerfil())
 && (this.getCRol()==castOther.getCRol());
   }
   
    @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCPerfil();
         result = 37 * result + this.getCRol();
         return result;
   }   


}


