package co.org.conte.sgm.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerfilRol generated by hbm2java
 */
@Entity
@Table(name="perfil_rol")
public class PerfilRol  implements java.io.Serializable {
    
    private PerfilRolId id;
    private Rol rol;
    private Perfil perfil;

    public PerfilRol() {
    }
	
    public PerfilRol(PerfilRolId id, Rol rol, Perfil perfil) {
        this.id = id;
        this.rol = rol;
        this.perfil = perfil;
    }
    
    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="CPerfil", column=@Column(name="c_perfil", nullable=false) ), 
        @AttributeOverride(name="CRol", column=@Column(name="c_rol", nullable=false) ) } )
    public PerfilRolId getId() {
        return this.id;
    }
    
    public void setId(PerfilRolId id) {
        this.id = id;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="c_rol", nullable=false, insertable=false, updatable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_perfil", nullable=false, insertable=false, updatable=false)
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
}