package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReferenciaPersonal generated by hbm2java
 */
@Entity
@Table(name="referencia_personal")
public class ReferenciaPersonal  implements java.io.Serializable {


     private Integer codigo;
     private Solicitud solicitud;
     private String nombres;
     private String parentesco;
     private String direccion;
     private String telefono;

    public ReferenciaPersonal() {
    }

	
    public ReferenciaPersonal(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public ReferenciaPersonal(Solicitud solicitud, String nombres, String direccion, String telefono) {
       this.solicitud = solicitud;
       this.nombres = nombres;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="codigo", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_solicitud", nullable=false)
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    
    @Column(name="nombres", length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    @Column(name="parentesco", length=180)
    public String getParentesco() {
        return parentesco;
    }

    public void setParentesco(String parentesco) {
        this.parentesco = parentesco;
    }
    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
}