package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RolPagina generated by hbm2java
 */
@Entity
@Table(name="rol_pagina")
public class RolPagina  implements java.io.Serializable {


     private RolPaginaId id;
     private Pagina pagina;
     private Rol rol;

    public RolPagina() {
    }

	
    public RolPagina(RolPaginaId id, Pagina pagina, Rol rol) {
        this.id = id;
        this.pagina = pagina;
        this.rol = rol;
    }
   
    @EmbeddedId   
    @AttributeOverrides( {
        @AttributeOverride(name="CRol", column=@Column(name="c_rol", nullable=false) ), 
        @AttributeOverride(name="CPagina", column=@Column(name="c_pagina", nullable=false) ) } )
    public RolPaginaId getId() {
        return this.id;
    }
    
    public void setId(RolPaginaId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="c_pagina", nullable=false, insertable=false, updatable=false)
    public Pagina getPagina() {
        return this.pagina;
    }
    
    public void setPagina(Pagina pagina) {
        this.pagina = pagina;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_rol", nullable=false, insertable=false, updatable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
}