package co.org.conte.sgm.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tecnico generated by hbm2java
 */
@Entity
@Table(name="tecnico"
)
public class Tecnico  implements java.io.Serializable {


     private Long codigo;
     private Ciudad ciudad;
     private String documento;
     private String nombres;
     private String primerApellido;
     private String segundoApellido;
     private Date fechaNacimiento;
     private String direccion;
     private String telefono;
     private String celular;
     private String email;
     private String matricula;
     private Date fechaExpedicion;
     private Date sancionInicio;
     private Date sancionFin;
     private Date vigencia;
     private Boolean notificacion;
     private Set<LogTecnico> logTecnicos = new HashSet(0);
     private Set<Sancion> sanciones = new HashSet(0);
     private Set<Solicitud> solicituds = new HashSet(0);

    public Tecnico() {
    }

    public Tecnico(Ciudad ciudad, String documento, String nombres, String primerApellido, String direccion, String telefono, String celular, String email, String matricula, Date fechaExpedicion, Date sancionInicio, Date sancionFin, Date vigencia, Set logTecnicos, Set solicituds) {
       this.ciudad = ciudad;
       this.documento = documento;
       this.nombres = nombres;
       this.primerApellido = primerApellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.email = email;
       this.matricula = matricula;
       this.fechaExpedicion = fechaExpedicion;
       this.sancionInicio = sancionInicio;
       this.sancionFin = sancionFin;
       this.vigencia = vigencia;
       this.logTecnicos = logTecnicos;
       this.solicituds = solicituds;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="codigo", unique=true, nullable=false)
    public Long getCodigo() {
        return this.codigo;
    }

     @Column(name="primer_apellido", length=45)
    public String getPrimerApellido() {
        return primerApellido;
    }

    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    @Column(name="segundo_apellido", length=45)
    public String getSegundoApellido() {
        return segundoApellido;
    }

    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", length=10)
    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    
    
    
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="c_ciudad")
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    
    @Column(name="documento", length=20)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    
    @Column(name="nombres", length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
       
    @Column(name="direccion", length=60)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="celular", length=20)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="matricula", length=20)
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    
    @Column(name="notificacion",  length=1)
    public Boolean isNotificacion() {
        return notificacion;
    }

    public void setNotificacion(Boolean notificacion) {
        this.notificacion = notificacion;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_expedicion", length=10)
    public Date getFechaExpedicion() {
        return this.fechaExpedicion;
    }
    
    public void setFechaExpedicion(Date fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="sancion_inicio", length=10)
    public Date getSancionInicio() {
        return this.sancionInicio;
    }
    
    public void setSancionInicio(Date sancionInicio) {
        this.sancionInicio = sancionInicio;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="sancion_fin", length=10)
    public Date getSancionFin() {
        return this.sancionFin;
    }
    
    public void setSancionFin(Date sancionFin) {
        this.sancionFin = sancionFin;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="vigencia", length=10)
    public Date getVigencia() {
        return this.vigencia;
    }
    
    public void setVigencia(Date vigencia) {
        this.vigencia = vigencia;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tecnico")
    public Set<LogTecnico> getLogTecnicos() {
        return this.logTecnicos;
    }
    
    public void setLogTecnicos(Set logTecnicos) {
        this.logTecnicos = logTecnicos;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tecnico")
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER,  mappedBy="tecnico")
    public Set<Sancion> getSanciones() {
        return sanciones;
    }

    public void setSanciones(Set<Sancion> sanciones) {
        this.sanciones = sanciones;
    }
}


