package co.org.conte.sgm.entity;
// Generated 12/10/2012 02:34:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TituloAcademico generated by hbm2java
 */
@Entity
@Table(name="titulo_academico")
public class TituloAcademico extends BaseEntity{


     private int codigo;
     private InstitucionEducativa institucionEducativa;
     private String nombre;
     private String descripcion;

    public TituloAcademico() {
    }

	
    public TituloAcademico(int codigo) {
        this.codigo = codigo;
    }
    public TituloAcademico(int codigo, InstitucionEducativa institucionEducativa, String nombre, String descripcion) {
       this.codigo = codigo;
       this.institucionEducativa = institucionEducativa;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="c_institucion")
    public InstitucionEducativa getInstitucionEducativa() {
        return this.institucionEducativa;
    }
    
    public void setInstitucionEducativa(InstitucionEducativa institucionEducativa) {
        this.institucionEducativa = institucionEducativa;
    }
    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}